[package]
name = "dev"
version = "0.1.0"
edition = "2021"

[features]
inspector = ["dep:bevy_egui", "dep:bevy-inspector-egui"]
world-inspector = ["inspector"]

[dependencies]
avian3d = { workspace = true, features = ["debug-plugin"] }
bevy = { workspace = true, default-features = true }
bevy_egui = { version = "0.39", optional = true }
bevy-inspector-egui = { version = "0.36", optional = true }
